sudo: false
language: ruby
rvm:
  - "2.2.2"
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
script:
  - bundle exec rspec spec
  - bundle exec cucumber features
notifications:
  email: false
  slack: cs169dev:OPMf1tPzfO3a4gz6gGTOFV7w
